(function(){
var g=false,i=null,m=true,aa=(new Date).getTime();var ba={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type",google_page_url:"url"},ca={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_analytics_uacct:"ga_wpids",
google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"};function da(){}da.prototype.Eb=function(){};da.prototype.Fb=function(){};da.prototype.Db=function(){};var o=i;function ea(a){o&&o.Eb(a)}function fa(a){o&&o.Fb(a)}function ga(a){o&&o.Db(a)}function r(){this.F=this.tb();this.ia=g;if(!this.F){this.ia=this.Va();this.ia||fa("Browser does not allow cookies")}}r.prototype.$="__gads=";r.prototype.N="GoogleAdServingTest=";r.prototype.cb=function(){return this.F};
r.prototype.setCookieInfo=function(a){this.A=a._cookies_[0];if(this.A!=i){this.F=this.A._value_;this.Cb()}};r.prototype.Ya=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
r.prototype.Xa=function(a){if(this.F!=i||!this.ia){ea("Skipping fetch cookie call");return}var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+ha(a)+"&domain="+ha(c);ea("Issuing a fetch cookie call with <a href='"+d+"'>"+d+"</a>");document.write("<"+b+' src="'+d+'"></'+b+">")};
r.prototype.Va=function(){document.cookie=this.N+"Good";var a=this.ua(this.N),b=a=="Good";if(b){var c=this.Ya(-1);document.cookie=this.N+"; expires="+c.toGMTString()}return b};r.prototype.tb=function(){var a=this.ua(this.$);a!=i?ea("Read first party cookie: "+a):fa("No first party cookie found");return a};r.prototype.ua=function(a){var b=document.cookie,c=b.indexOf(a),d=i;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};
r.prototype.Cb=function(){if(this.A==i)fa("Skipping cookie creation: no cookie info");else if(this.F==i)ga("Skipping cookie creation: no cookie value");else{var a=new Date;a.setTime(1000*this.A._expires_);var b=this.A._domain_,c=this.$+this.F+"; expires="+a.toGMTString()+"; path="+this.A._path_+"; domain=."+b;document.cookie=c;ea("Written cookie: "+c)}};function ia(a,b){var c;return a?(c=parseFloat(a))?c:b:b}
function ja(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;while(c)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=i}return b.toString()}else if(ka("msie")&&!window.opera){var c=i;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=
0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=i){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var la=la||{},s=this;var na=function(a,b,c){var d=a.split("."),e=c||s,f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);while(d.length&&(f=d.shift()))if(!d.length&&ma(b))e[f]=b;else e=e[f]?e[f]:(e[f]={})},oa=function(a,b){var c=a.split("."),d=b||s;for(var e;e=c.shift();)if(d[e])d=d[e];else return i;return d};
var t=function(a){var b=typeof a;if(b=="object")if(a){if(typeof a.length=="number"&&typeof a.splice!="undefined"&&!pa(a,"length"))return"array";if(typeof a.call!="undefined")return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},qa=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return m;return g};
if(Object.prototype.propertyIsEnumerable)var pa=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):qa(a,b)};else pa=qa;var ma=function(a){return typeof a!="undefined"};var ra=function(a){var b=t(a);return b=="array"||b=="object"&&typeof a.length=="number"};
var u=function(a){return t(a)=="function"},sa=function(a){var b=t(a);return b=="object"||b=="array"||b=="function"},va=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(ta)){var b=a[ta];if(b)return b}a[ta]||(a[ta]=++ua);return a[ta]},ta="closure_hashCode_",ua=0,v=function(a,b){var c=a.Gb;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,c);c=d}b=a.Ib||b;a=a.Hb||a;var e,f=b||s;e=c?function(){var h=Array.prototype.slice.call(arguments);h.unshift.apply(h,c);return a.apply(f,
h)}:function(){return a.apply(f,arguments)};e.Gb=c;e.Ib=b;e.Hb=a;return e},wa=Date.now||function(){return(new Date).getTime()},xa=function(a,b,c){na(a,b,c)},x=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.prototype.constructor=a};var ya=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);var d=c==i?0:c<0?Math.max(0,a.length+c):c;for(var e=d;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},za=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else{var d=a.length,e=typeof a=="string"?a.split(""):a;for(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)}},Aa=function(a,b){var c=ya(a,b),d;if(d=c!=-1)Array.prototype.splice.call(a,c,1).length==1;return d};
var Ba=function(a){if(t(a)=="array")return a.concat();else{var b=[];for(var c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var Ca=function(a,b){this.x=ma(a)?a:0;this.y=ma(b)?b:0};Ca.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var y=function(a,b){this.width=a;this.height=b};y.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};y.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};y.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};y.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
y.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Da=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var Ea=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ka=function(a,b){if(b)return a.replace(Fa,"&amp;").replace(Ga,"&lt;").replace(Ha,"&gt;").replace(Ia,"&quot;");else{if(!Ja.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Fa,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(Ga,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Ha,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Ia,"&quot;");return a}},Fa=/&/g,Ga=/</g,Ha=/>/g,Ia=/\"/g,Ja=/[&<>\"]/,La=function(a,b){var c=b.length;for(var d=0;d<c;d++){var e=
c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},Na=function(a,b){var c=0,d=Ea(String(a)).split("."),e=Ea(String(b)).split("."),f=Math.max(d.length,e.length);for(var h=0;c==0&&h<f;h++){var j=d[h]||"",k=e[h]||"",l=new RegExp("(\\d*)(\\D*)","g"),n=new RegExp("(\\d*)(\\D*)","g");do{var p=l.exec(j)||["","",""],q=n.exec(k)||["","",""];if(p[0].length==0&&q[0].length==0)break;var w=p[1].length==0?0:parseInt(p[1],10),L=q[1].length==0?0:parseInt(q[1],
10);c=Ma(w,L)||Ma(p[2].length==0,q[2].length==0)||Ma(p[2],q[2])}while(c==0)}return c},Ma=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za=function(){if(s.navigator)return s.navigator.userAgent;return i},$a=function(){var a=g,b=g,c=g,d=g,e=g,f=g,h=g,j=g,k=g,l="",n=Za();if(n){var p=s.navigator;a=n.indexOf("Opera")==0;b=!a&&n.indexOf("MSIE")!=-1;c=!a&&n.indexOf("WebKit")!=-1;k=c&&n.indexOf("Mobile")!=-1;d=!a&&!c&&p.product=="Gecko";e=d&&p.vendor=="Camino";var q,w;if(s.opera)q=s.opera.version();else{if(d)w=/rv\:([^\);]+)(\)|;)/;else if(b)w=/MSIE\s+([^\);]+)(\)|;)/;else if(c)w=/WebKit\/(\S+)/;if(w){w.test(n);
q=RegExp.$1}}l=p.platform||"";f=l.indexOf("Mac")!=-1;h=l.indexOf("Win")!=-1;j=l.indexOf("Linux")!=-1}Oa=a;Pa=b;Qa=d;Ra=e;Sa=c;Ta=k;Ua=q;Va=l;Wa=f;Xa=h;Ya=j};$a();var ab=Oa,z=Pa,fb=Qa,A=Sa,gb=Ta;var B=function(a){return Na(Ua,a)>=0};var hb;var ib=function(){hb||(hb=new C);return hb},kb=function(a){return a?new C(jb(a)):ib()};
var lb=function(a){return typeof a=="string"?document.getElementById(a):a},mb=lb,ob=function(a,b){Da(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in nb)a.setAttribute(nb[d],c);else a[d]=c})},nb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder"},pb=function(a){var b=a||s||window,c=b.document;if(A&&!B("500")&&
!gb){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new y(b.innerWidth,d)}var f=kb(c),h=f.$a()=="CSS1Compat"&&(!ab||ab&&B("9.50"))?c.documentElement:c.body;return new y(h.clientWidth,h.clientHeight)};var qb=function(a,b){a.appendChild(b)},D=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):i};
var rb=A&&Na(Ua,"521")<=0,sb=function(a,b){if(typeof a.contains!="undefined"&&!rb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);while(b&&a!=b)b=b.parentNode;return b==a},jb=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},tb=function(a){if(a&&typeof a.length=="number")if(sa(a))return typeof a.item=="function"||typeof a.item=="string";else if(u(a))return typeof a.item=="function";return g},
C=function(a){this.s=a||s.document||document};C.prototype.ab=function(){return this.s};C.prototype.Oa=function(a,b){if(z&&b&&b.name)a="<"+a+' name="'+Ka(b.name)+'">';var c=this.createElement(a);b&&ob(c,b);if(arguments.length>2){function d(h){if(h)this.appendChild(c,typeof h=="string"?this.createTextNode(h):h)}for(var e=2;e<arguments.length;e++){var f=arguments[e];ra(f)&&!(sa(f)&&f.nodeType>0)?za(tb(f)?Ba(f):f,d,this):d.call(this,f)}}return c};C.prototype.createElement=function(a){return this.s.createElement(a)};
C.prototype.createTextNode=function(a){return this.s.createTextNode(a)};C.prototype.$a=function(){if(this.s.compatMode)return this.s.compatMode;if(A){var a=this.Oa("div",{style:"position:absolute;width:0;height:0;width:1"}),b=a.style.width=="1px"?"BackCompat":"CSS1Compat";return this.s.compatMode=b}return"BackCompat"};
C.prototype.oa=function(){var a=this.s,b,c;if(!A&&a.compatMode=="CSS1Compat"){b=a.documentElement.scrollLeft;c=a.documentElement.scrollTop}else{b=a.body.scrollLeft;c=a.body.scrollTop}return new Ca(b,c)};C.prototype.appendChild=qb;C.prototype.removeNode=D;C.prototype.contains=sb;var ub,vb=function(a,b){var c=jb(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return i};
var wb=function(a){return vb(a,"position")||(a.currentStyle?a.currentStyle.position:i)||a.style.position},xb=function(a){var b;b=a?a.nodeType==9?a:jb(a):ib().ab();if(z&&b.compatMode!="CSS1Compat")return b.body;return b.documentElement},yb=function(a){var b=jb(a),c=fb&&b.getBoxObjectFor&&wb(a)=="absolute"&&(a.style.top==""||a.style.left=="");if(typeof ub=="undefined")ub=Ra&&!B("1.8.0.11");var d=new Ca(0,0),e=xb(b);if(a==e)return d;var f=i,h;if(a.getBoundingClientRect&&!c){h=a.getBoundingClientRect();
var j=kb(b).oa();d.x=h.left+j.x;d.y=h.top+j.y}else if(b.getBoxObjectFor&&!c&&!ub){h=b.getBoxObjectFor(a);var k=b.getBoxObjectFor(e);d.x=h.screenX-k.screenX;d.y=h.screenY-k.screenY}else{f=a;do{d.x+=f.offsetLeft;d.y+=f.offsetTop;if(f!=a)d.x+=f.clientLeft||0;if(f!=a)d.y+=f.clientTop||0;if(A&&wb(f)=="fixed"){d.x+=b.body.scrollLeft;d.y+=b.body.scrollTop;break}f=f.offsetParent}while(f&&f!=a);if(ab||A&&wb(a)=="absolute")d.y-=b.body.offsetTop;f=a.offsetParent;while(f&&f!=b.body){d.x-=f.scrollLeft;if(!ab||
f.tagName!="TR")d.y-=f.scrollTop;f=f.offsetParent}}if(fb&&a.getBoundingClientRect){var l=wb(a);if(l=="static"||l=="relative"){d.x=Math.floor(d.x);d.y=Math.floor(d.y)}}return d},zb=function(a){var b=new Ca;if(a.nodeType==1)if(a.getBoundingClientRect){var c=a.getBoundingClientRect();b.x=c.left;b.y=c.top}else{var d=kb(a).oa(),e=yb(a);b.x=e.x-d.x;b.y=e.y-d.y}else{b.x=a.clientX;b.y=a.clientY}return b},Ab=function(a){var b=jb(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);
c=d.queryCommandValue("FontName")}if(!c){c=vb(a,"fontFamily")||(a.currentStyle?a.currentStyle.fontFamily:i)||a.style.fontFamily;if(ab&&Ya)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return La(c,"\"'")};var Bb=document,E=navigator,F=window;
function Cb(){var a=Bb.cookie,b=Math.round((new Date).getTime()/1000),c=F.google_analytics_domain_name,d=typeof c=="undefined"?Db("auto"):Db(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,h=a.indexOf("__utmc="+d)>-1,j,k={};if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&h?j[3]+"":F&&F.gaGlobal&&F.gaGlobal.sid?F.gaGlobal.sid:b+"";k.vid=j[0]+"."+j[1];k.from_cookie=m}else{k.sid=F&&F.gaGlobal&&F.gaGlobal.sid?F.gaGlobal.sid:b+"";k.vid=F&&F.gaGlobal&&F.gaGlobal.vid?
F.gaGlobal.vid:(Eb()^Fb()&2147483647)+"."+b;k.from_cookie=g}k.dh=d;k.hid=F&&F.gaGlobal&&F.gaGlobal.hid?F.gaGlobal.hid:Eb();F.gaGlobal=k;return k}function Eb(){return Math.round(Math.random()*2147483647)}
function Fb(){var a=Bb.cookie?Bb.cookie:"",b=F.history.length,c,d,e=[E.appName,E.version,E.language?E.language:E.browserLanguage,E.platform,E.userAgent,E.javaEnabled()?1:0].join("");if(F.screen)e+=F.screen.width+"x"+F.screen.height+F.screen.colorDepth;else if(F.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=Bb.referrer?Bb.referrer:"";c=e.length;while(b>0)e+=b--^c++;return Gb(e)}
function Gb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Db(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Bb.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Gb(a.toLowerCase())};var G=function(){};G.prototype.na=g;G.prototype.dispose=function(){if(!this.na){this.b();this.na=m}};G.prototype.b=function(){};var Hb=function(a){if(/^\s*$/.test(a))return g;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x1f\x7f-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},Ib=function(a){String(a);if(Hb(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Jb=i,Kb=function(a){Jb||(Jb=new H);return Jb.serialize(a)},H=function(){};
H.prototype.serialize=function(a){var b=[];this.Y(a,b);return b.join("")};H.prototype.Y=function(a,b){switch(typeof a){case "string":this.xa(a,b);break;case "number":this.zb(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==i){b.push("null");break}if(t(a)=="array"){this.yb(a,b);break}this.Ab(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var Lb={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"};H.prototype.xa=function(a,b){b.push('"',a.replace(/[\\\"\x00-\x1f\x80-\uffff]/g,function(c){if(c in Lb)return Lb[c];var d=c.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return Lb[c]=e+d.toString(16)}),'"')};H.prototype.zb=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};
H.prototype.yb=function(a,b){var c=a.length;b.push("[");var d="";for(var e=0;e<c;e++){b.push(d);this.Y(a[e],b);d=","}b.push("]")};H.prototype.Ab=function(a,b){b.push("{");var c="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b.push(c);this.xa(d,b);b.push(":");this.Y(e,b);c=","}}b.push("}")};var I="SETUP_ACK",Mb={},Ob=function(a,b){var c=b||Nb,d=c.length,e="";while(a-- >0)e+=c.charAt(Math.floor(Math.random()*d));return e},Nb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var Pb=function(){};x(Pb,G);var J=function(a){this.a=a;this.L=[];this.Mb=v(this.Ta,this)};x(J,Pb);J.prototype.l=0;J.prototype.G=1;J.prototype.T=g;J.prototype.Bb=0;J.prototype.connect=function(){this.V=window.parent==this.a.f?this.G:this.l;if(this.V==this.l){this.j=this.a.u;this.j.XPC_toOuter=v(this.pa,this)}else this.ca()};
J.prototype.ca=function(){var a=m;try{if(!this.j)this.j=window.frameElement;if(this.j&&this.j.XPC_toOuter){this.sa=this.j.XPC_toOuter;this.j.XPC_toOuter.XPC_toInner=v(this.pa,this);a=g;this.send("tp",I);this.a.k()}}catch(b){}if(a){if(!this.Ea)this.Ea=v(this.ca,this);window.setTimeout(this.Ea,100)}};J.prototype.D=function(a){if(this.V==this.l&&!this.a.h()&&a==I){this.sa=this.j.XPC_toOuter.XPC_toInner;this.a.k()}else throw Error("Got unexpected transport message.");};
J.prototype.pa=function(a,b){if(!this.T&&this.L.length==0)this.a.m(a,b);else{this.L.push({serviceName:a,payload:b});if(this.L.length==1)this.Bb=window.setTimeout(this.Mb,1)}};J.prototype.Ta=function(){while(this.L.length){var a=this.L.shift();this.a.m(a.serviceName,a.payload)}};J.prototype.send=function(a,b){this.T=m;this.sa(a,b);this.T=g};J.prototype.b=function(){J.o.b.call(this);this.sa=i;this.j=i};var K=function(a){this.a=a;this.M=this.a.c.ppu;this.Pb=this.a.c.lpu;this.W=[]},Qb,Rb,Sb;x(K,Pb);K.prototype.X=0;K.prototype.z=g;K.prototype.connect=function(){this.Ma()};K.prototype.Ma=function(){var a=this.a.name+"_msg";this.kb=this.ha(a);this.nb=window.frames[a];a=this.a.name+"_ack";this.Ba=this.ha(a);this.Da=window.frames[a];this.ea()};
K.prototype.ha=function(a){var b=ib().createElement("iframe"),c=b.style;c.position="absolute";c.top="-10px";c.left="10px";c.width="1px";c.height="1px";b.id=b.name=a;b.src=this.M+"#INITIAL";document.body.appendChild(b);return b};
K.prototype.ea=function(){this.Ia&&window.clearTimeout(this.Ia);if(this.qa("msg")&&this.qa("ack")){this.lb=new Tb(this,this.a.f.frames[this.a.name+"_msg"],v(this.rb,this));this.Ca=new Tb(this,this.a.f.frames[this.a.name+"_ack"],v(this.qb,this));this.ga()}else{if(!this.Ha)this.Ha=v(this.ea,this);this.Ia=window.setTimeout(this.Ha,100)}};K.prototype.qa=function(a){try{var b=this.a.f.frames[this.a.name+"_"+a];if(!b||b.location.href.indexOf(this.Pb)!=0)return g}catch(c){return g}return m};
K.prototype.ga=function(){var a=this.a.f.frames;if(a[this.a.name+"_ack"]&&a[this.a.name+"_msg"]){this.mb=new Ub(this.M,this.nb);this.O=new Ub(this.M,this.Da);window.setTimeout(v(function(){this.mb.send("SETUP");this.Sb=m;this.z=m},this),100)}else{if(!this.Ja)this.Ja=v(this.ga,this);window.setTimeout(this.Ja,100)}};K.prototype.fa=function(){if(this.xb&&this.Qb){this.a.k();if(this.I){for(var a=0,b;a<this.I.length;a++){b=this.I[a];this.a.m(b.service,b.payload)}delete this.I}}};
K.prototype.rb=function(a){if(a=="SETUP"){if(!this.O)return;this.O.send(I);this.xb=m;this.fa()}else if(this.a.h()||this.xb){var b=a.indexOf("|"),c=a.substring(0,b),d=a.substring(b+1);b=c.indexOf(",");if(b==-1){var e=c;this.O.send("ACK:"+e);this.la(d)}else{var e=c.substring(0,b);this.O.send("ACK:"+e);var f=c.substring(b+1).split("/");f[0]=parseInt(f[0],10);f[1]=parseInt(f[1],10);if(f[0]==1)this.ta=[];this.ta.push(d);if(f[0]==f[1]){this.la(this.ta.join(""));delete this.ta}}}};
K.prototype.qb=function(a){if(a==I){this.z=g;this.Qb=m;this.fa()}else if(this.a.h()){if(!this.z)return;var b=parseInt(a.split(":")[1],10);if(b==this.X){this.z=g;this.wa()}}};K.prototype.wa=function(){if(this.z||!this.W.length)return;var a=this.W.shift();++this.X;this.mb.send(this.X+a);this.z=m};K.prototype.la=function(a){var b=a.indexOf(":"),c=a.substr(0,b),d=a.substring(b+1);this.a.h()?this.a.m(c,d):(this.I||(this.I=[])).push({service:c,payload:d})};K.prototype.H=3800;
K.prototype.send=function(a,b){var c=a+":"+b;if(!z||b.length<=this.H)this.W.push("|"+c);else{var d=b.length,e=Math.ceil(d/this.H),f=0,h=1;while(f<d){this.W.push(","+h+"/"+e+"|"+c.substr(f,this.H));h++;f+=this.H}}this.wa()};K.prototype.b=function(){K.o.b.call(this);var a=Vb;Aa(a,this.lb);Aa(a,this.Ca);this.lb=this.Ca=i;D(this.kb);D(this.Ba);this.kb=this.Ba=i;this.nb=this.Da=i};
var Vb=[],Xb=function(){var a=g;try{for(var b=0,c=Vb.length;b<c;b++)a=a||Vb[b].receive()}catch(d){Vb[b].e.a.ob();if(!Vb.length)return}var e=wa();if(a)Qb=e;var f=e-Qb<1000?10:100;Rb=window.setTimeout(Wb,f)},Wb=v(Xb,K),$b=function(){Qb=wa();Rb&&window.clearTimeout(Rb);Rb=window.setTimeout(Wb,10)},Ub=function(a,b){this.M=a;this.wb=b;this.ka=0};
Ub.prototype.send=function(a){this.ka=++this.ka%2;var b=this.M+"#"+this.ka+encodeURIComponent(a);try{if(A)this.wb.location.href=b;else this.wb.location.replace(b)}catch(c){}Sb=wa()};var Tb=function(a,b,c){this.e=a;this.sb=b;this.Jb=c;this.Ra=this.sb.location.href.split("#")[0]+"#INITIAL";Vb.push(this);$b()};Tb.prototype.receive=function(){var a=this.sb.location.href;if(a!=this.Ra){this.Ra=a;var b=a.split("#")[1];if(b){b=b.substr(1);this.Jb(decodeURIComponent(b))}return m}else return g};var M=function(a,b){G.call(this);this.ib=b;this.t=[];this.Pa(a)};x(M,G);M.prototype.P=i;M.prototype.Q=i;M.prototype.C=function(a){this.P=a};M.prototype.za=function(a){this.Q=a};M.prototype.i=function(){if(this.t.length)return this.t.pop();return this.ja()};M.prototype.w=function(a){this.t.length<this.ib?this.t.push(a):this.ma(a)};M.prototype.Pa=function(a){if(a>this.ib)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.t.push(this.ja())};
M.prototype.ja=function(){return this.P?this.P():{}};M.prototype.ma=function(a){if(this.Q)this.Q(a);else if(u(a.dispose))a.dispose();else for(var b in a)delete a[b]};M.prototype.b=function(){M.o.b.call(this);var a=this.t;while(a.length)this.ma(a.pop());delete this.t};var N=function(a,b){this.type=a;this.target=b;this.currentTarget=this.target};x(N,G);N.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};N.prototype.B=g;N.prototype.U=m;N.prototype.stopPropagation=function(){this.B=m};N.prototype.preventDefault=function(){this.U=g};var O=function(a,b){a&&this.init(a,b)};x(O,N);O.prototype.type=i;O.prototype.target=i;O.prototype.relatedTarget=i;O.prototype.offsetX=0;O.prototype.offsetY=0;O.prototype.clientX=0;O.prototype.clientY=0;O.prototype.screenX=0;O.prototype.screenY=0;O.prototype.button=0;O.prototype.keyCode=0;O.prototype.charCode=0;O.prototype.ctrlKey=g;O.prototype.altKey=g;O.prototype.shiftKey=g;O.prototype.metaKey=g;O.prototype.g=i;
O.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;this.relatedTarget=a.relatedTarget?a.relatedTarget:this.type=="mouseover"?a.fromElement:this.type=="mouseout"?a.toElement:i;this.offsetX=typeof a.layerX=="number"?a.layerX:a.offsetX;this.offsetY=typeof a.layerY=="number"?a.layerY:a.offsetY;this.clientX=typeof a.clientX=="number"?a.clientX:a.pageX;this.clientY=typeof a.clientY=="number"?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(this.type=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.g=a;delete this.U;delete this.B};O.prototype.stopPropagation=function(){this.B=m;if(this.g.stopPropagation)this.g.stopPropagation();else this.g.cancelBubble=m};
O.prototype.preventDefault=function(){this.U=g;if(this.g.preventDefault)this.g.preventDefault();else{this.g.returnValue=g;try{this.g.keyCode=-1}catch(a){}}};O.prototype.Za=function(){return this.g};O.prototype.b=function(){O.o.b.call(this);this.g=i};var P=function(){},ac=0;P.prototype.S=i;P.prototype.listener=i;P.prototype.proxy=i;P.prototype.src=i;P.prototype.type=i;P.prototype.capture=i;P.prototype.handler=i;P.prototype.key=0;P.prototype.removed=g;P.prototype.da=g;P.prototype.init=function(a,b,c,d,e,f){if(u(a))this.S=m;else if(a&&a.handleEvent&&u(a.handleEvent))this.S=g;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.da=g;this.key=++ac;this.removed=g};
P.prototype.handleEvent=function(a){if(this.S)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};var bc={},Q={},cc={},dc=new M(0,600);dc.C(function(){return{r:0}});dc.za(function(a){a.r=0});var R=new M(0,600);R.C(function(){return[]});R.za(function(a){a.length=0;delete a.K;delete a.ra});var ec=new M(0,600);ec.C(function(){var a=function(b){return fc.call(a.src,a.key,b)};return a});var gc=function(){return new P},hc=new M(0,600);hc.C(gc);
var ic=function(){return new O},jc=function(){var a=i;if(z){a=new M(0,600);a.C(ic)}return a},kc=jc(),lc="on",mc={},nc=function(a,b,c,d,e){if(b)if(t(b)=="array"){for(var f=0;f<b.length;f++)nc(a,b[f],c,d,e);return i}else{var h=!!d,j=Q;b in j||(j[b]=dc.i());j=j[b];if(!(h in j)){j[h]=dc.i();j.r++}j=j[h];var k=va(a),l,n;if(j[k]){l=j[k];for(var f=0;f<l.length;f++){n=l[f];if(n.listener==c&&n.handler==e){if(n.removed)break;return l[f].key}}}else{l=j[k]=R.i();j.r++}var p=ec.i();p.src=a;n=hc.i();n.init(c,p,
a,b,h,e);var q=n.key;p.key=q;l.push(n);bc[q]=n;cc[k]||(cc[k]=R.i());cc[k].push(n);if(a.addEventListener){if(a==s||!a.Lb)a.addEventListener(b,p,h)}else a.attachEvent(oc(b),p);return q}else throw Error("Invalid event type");},pc=function(a,b,c,d,e){if(t(b)=="array"){for(var f=0;f<b.length;f++)pc(a,b[f],c,d,e);return i}var h=!!d,j=qc(a,b,h);if(!j)return g;for(var f=0;f<j.length;f++)if(j[f].listener==c&&j[f].capture==h&&j[f].handler==e)return rc(j[f].key);return g},rc=function(a){if(!bc[a])return g;var b=
bc[a];if(b.removed)return g;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==s||!c.Lb)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(oc(d),e);var h=va(c),j=Q[d][f][h];if(cc[h]){var k=cc[h];Aa(k,b);k.length==0&&delete cc[h]}b.removed=m;j.ra=m;sc(d,f,h,j);delete bc[a];return m},sc=function(a,b,c,d){if(!d.K)if(d.ra){for(var e=0,f=0;e<d.length;e++){if(d[e].removed){hc.w(d[e]);continue}if(e!=f)d[f]=d[e];f++}d.length=f;d.ra=g;if(f==0){R.w(d);delete Q[a][b][c];Q[a][b].r--;
if(Q[a][b].r==0){dc.w(Q[a][b]);delete Q[a][b];Q[a].r--}if(Q[a].r==0){dc.w(Q[a]);delete Q[a]}}}},qc=function(a,b,c){var d=Q;if(b in d){d=d[b];if(c in d){d=d[c];var e=va(a);if(d[e])return d[e]}}return i},oc=function(a){if(a in mc)return mc[a];return mc[a]=lc+a},uc=function(a,b,c,d){var e=1,f=Q;if(b in f){f=f[b];if(c in f){f=f[c];var h=va(a);if(f[h]){var j=f[h];if(j.K)j.K++;else j.K=1;try{var k=j.length;for(var l=0;l<k;l++){var n=j[l];if(n&&!n.removed)e&=tc(n,d)!==g}}finally{j.K--;sc(b,c,h,j)}}}}return Boolean(e)},
tc=function(a,b){var c=a.handleEvent(b);a.da&&rc(a.key);return c},fc=function(a,b){if(!bc[a])return m;var c=bc[a],d=c.type,e=Q;if(!(d in e))return m;e=e[d];var f;if(z){var h=b||oa("window.event"),j=m in e;if(j){if(h.keyCode<0||h.returnValue!=undefined)return m;vc(h)}va(c.src);var k=kc.i();k.init(h,this);f=m;try{if(j){var l=R.i();for(var n=k.currentTarget;n;n=n.parentNode)l.push(n);for(var p=l.length-1;!k.B&&p>=0;p--){k.currentTarget=l[p];f&=uc(l[p],d,m,k)}for(var p=0;!k.B&&p<l.length;p++){k.currentTarget=
l[p];f&=uc(l[p],d,g,k)}}else f=tc(c,k)}finally{if(l){l.length=0;R.w(l)}k.dispose();kc.w(k)}return f}var q=new O(b,this);try{f=tc(c,q)}finally{q.dispose()}return f},vc=function(a){var b=g;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=m}if(b||a.returnValue==undefined)a.returnValue=m};var S=function(a){this.a=a;this.Ob=this.a.c.pru;this.pb=this.a.c.ifrid;A&&wc()};x(S,Pb);if(A){var xc=[],yc=0,wc=function(){yc||(yc=window.setTimeout(function(){zc()},1000))},zc=function(a){var b=wa(),c=a||3000;while(xc.length&&b-xc[0].timestamp>=c){var d=xc.shift().iframeElement;D(d)}yc=window.setTimeout(Ac,1000)},Ac=function(){zc()}}S.prototype.connect=function(){this.send("tp","SETUP")};S.prototype.D=function(a){if(a=="SETUP"){this.send("tp",I);this.a.k()}else a==I&&this.a.k()};
S.prototype.send=function(a,b){if(z){var c=document.createElement("div");c.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';var d=c.childNodes[0];d.xpcOnload=Bc}else{var d=document.createElement("iframe");A?xc.push({timestamp:wa(),iframeElement:d}):nc(d,"load",Bc)}var e=d.style;e.visibility="hidden";e.width=d.style.height="0px";e.position="absolute";var f=this.Ob;f+="#"+this.a.name;if(this.pb)f+=","+this.pb;f+="|"+a+":"+encodeURIComponent(b);d.src=f;document.body.appendChild(d)};
var Bc=function(){D(this);this.xpcOnload=i};window.xpcRelay=function(a,b){var c=b.indexOf(":"),d=b.substring(0,c),e=b.substring(c+1);Mb[a].m(d,decodeURIComponent(e))};S.prototype.b=function(){S.o.b.call(this);A&&zc(0)};var T=function(a){this.a=a};x(T,Pb);var Cc=g,Ec=function(){if(!Cc){nc(u(window.postMessage)?window:document,"message",Dc,g,T);Cc=m}},Dc=function(a){var b=a.Za().data,c=b.indexOf("|"),d=b.indexOf(":");if(c==-1||d==-1)return;var e=b.substring(0,c),f=b.substring(c+1,d),h=b.substring(d+1),j=Mb[e];j&&j.m(f,h)};T.prototype.D=function(a){switch(a){case "SETUP":this.send("tp",I);case I:this.a.k();break}};T.prototype.connect=function(){Ec();this.send("tp","SETUP")};
T.prototype.send=function(a,b){var c=this.a.f;if(!c)return;var d=u(window.postMessage)?c:c.document;this.send=function(e,f){d.postMessage(this.a.name+"|"+e+":"+f,"*")};this.send(a,b)};T.prototype.b=function(){T.o.b.call(this);pc(document,"message",this.Rb,g,this)};var U=function(a){this.a=a;this.Fa=a.at||"";this.vb=a.rat||"";Fc();this[Gc]=this.J;this[Hc]=this.Na};x(U,Pb);
var Ic="GRPC____NIXVBS_wrapper",Jc="GRPC____NIXVBS_get_wrapper",Gc="GRPC____NIXJS_handle_message",Hc="GRPC____NIXJS_create_channel",Kc="GRPC____NIXVBS_container",Fc=function(){if(window.nix_setup_complete)return;var a="Class "+Ic+"\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport."+Gc+
"(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport."+Hc+"(channel)\nEnd Sub\nPublic Sub "+Kc+"()\n End Sub\nEnd Class\n Function "+Jc+"(transport, auth)\nDim wrap\nSet wrap = New "+Ic+"\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet "+Jc+" = wrap\nEnd Function";try{window.execScript(a,"vbscript");window.nix_setup_complete=m}catch(b){}};U.prototype.l=0;U.prototype.G=1;U.prototype.v=g;U.prototype.n=i;
U.prototype.connect=function(){this.V=window.parent==this.a.f?this.G:this.l;this.V==this.l?this.ba():this.aa()};U.prototype.ba=function(){if(this.v)return;var a=this.a.u;try{a.contentWindow.opener=window[Jc](this,this.Fa);this.v=m}catch(b){}this.v||window.setTimeout(v(this.ba,this),100)};
U.prototype.aa=function(){if(this.v)return;try{var a=window.opener;if(a&&Kc in a){this.n=a;var b=this.n.GetAuthToken();if(b!=this.vb)return;this.n.CreateChannel(window[Jc](this,this.Fa));this.v=m;this.a.k()}}catch(c){return}this.v||window.setTimeout(v(this.aa,this),100)};U.prototype.Na=function(a){this.n=a;var b=this.n.GetAuthToken();if(b!=this.vb)return;this.a.k()};U.prototype.J=function(a,b){function c(){this.a.m(a,b)}window.setTimeout(v(c,this),1)};
U.prototype.send=function(a,b){this.n.SendMessage(a,b)};U.prototype.b=function(){U.o.b.call(this);this.n=i};var V=function(a){this.c=a;this.name=this.c.cn||Ob(10);this.ya={};Mb[this.name]=this;nc(window,"unload",Lc)};x(V,G);V.prototype.e=i;V.prototype.Z=1;V.prototype.h=function(){return this.Z==2};V.prototype.f=i;V.prototype.u=i;V.prototype.Aa=function(a){this.f=a};
V.prototype.Qa=function(){if(this.e)return;if(!this.c.tp)if(u(document.postMessage)||u(window.postMessage))this.c.tp=1;else if(fb)this.c.tp=2;else if(z&&this.c.pru)this.c.tp=3;else if(z)this.c.tp=6;else if(this.c.lpu&&this.c.ppu)this.c.tp=4;switch(this.c.tp){case 1:this.e=new T(this);break;case 6:this.e=new U(this);break;case 2:this.e=new J(this);break;case 3:this.e=new S(this);break;case 4:this.e=new K(this);break}if(!this.e)throw Error("CrossPageChannel: No suitable transport found!");};
V.prototype.Sa=g;V.prototype.La=g;V.prototype.connect=function(a){this.Kb=a;if(this.Sa){this.La=m;return}if(this.c.ifrid)this.u=typeof this.c.ifrid=="string"?document.getElementById(this.c.ifrid):this.c.ifrid;if(this.u){var b=this.u.contentWindow;b||(b=window.frames[this.c.ifrid]);this.Aa(b)}if(!this.f)if(window==top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");else this.Aa(window.parent);this.Qa();this.e.connect()};
V.prototype.close=function(){if(!this.h())return;this.Z=3;this.e.dispose();this.e=i};V.prototype.k=function(){if(this.h())return;this.Z=2;this.Kb()};V.prototype.ob=function(){this.close()};V.prototype.ub=function(a,b,c){this.ya[a]={name:a,callback:b,jsonEncoded:!!c}};V.prototype.send=function(a,b){if(!this.h())return;if(this.f.closed){this.close();return}if(sa(b))b=Kb(b);this.e.send(a,b)};
V.prototype.m=function(a,b){if(!a||a=="tp")this.e.D(b);else if(this.h()){var c=this.ya[a];if(c){if(c.jsonEncoded)try{b=Ib(b)}catch(d){return}c.callback(b)}}};V.prototype.b=function(){V.o.b.call(this);this.close();this.f=i;this.u=i;delete this.ya;Mb[this.name]=i};var Lc=function(){for(var a in Mb){var b=Mb[a];b&&b.dispose()}};var Mc=function(a){var b=a||document.location.protocol+"//"+document.location.host;return b+"/robots.txt"};var W=function(a,b){this.q=b.width;this.p=b.height;this.Ga=Ob(10);this.Nb=this.bb(a,document);this.R=g;this.d=b;this.d.src=this.jb(document,a);this.hb(this.db(document))};W.prototype.jb=function(a,b){return b+(b.indexOf("?")==-1?"?":"&")+"w="+this.q+"&h="+this.p+"&xpc="+this.Ga+"&p="+escape(a.location.protocol+"//"+a.location.host)};W.prototype.db=function(){var a={};a.ifrid=this.d.id;a.pu=this.d.src;a.cn=this.Ga;a.ppu=Mc(this.Nb);a.lpu=Mc();return a};
W.prototype.hb=function(a){this.a=new V(a);this.a.ub("expandable_ad",v(this.J,this));this.a.connect(function(){});window.setTimeout(v(this.fb,this),30000)};W.prototype.fb=function(){this.a&&!this.a.h()&&this.a.dispose()};W.prototype.bb=function(a,b){var c=a.indexOf("//"),d=c>0,e=d?a.substring(0,c):b.location.protocol,f=d?a.substring(c+2):b.location.host,h=f.indexOf("/");if(d&&h>0)f=f.substring(0,h);return e+"//"+f};
W.prototype.J=function(a){var b=a.split("_"),c=b[0];if(c=="expand")this.gb(b);else c=="collapse"&&this.eb()};W.prototype.va=function(a){this.a.send("expandable_ad",a)};W.prototype.gb=function(a){if(this.R)return;var b,c;for(var d in a){var e=a[d].charAt(0);if(e=="w")b=parseInt(a[d].substring(1),10);else if(e=="h")c=parseInt(a[d].substring(1),10)}var f=this.Ua(b,c);this.Wa(b,c,f);this.va("ok_expand_w"+b+"_h"+c+"_d"+f)};
W.prototype.eb=function(){if(!this.R)return;this.Ka();this.va("ok_collapse_w"+this.q+"_h"+this.p)};W.prototype.Ka=function(){this.d.style.width=this.q+"px";this.d.style.height=this.p+"px";this.d.style.left="0";this.d.style.top="0";this.d.style.zIndex=i;this.d.parentNode.style.zIndex=i;this.R=g};
W.prototype.Wa=function(a,b,c){this.d.style.position="absolute";this.d.style.width=a+"px";this.d.style.height=b+"px";this.d.style.zIndex=9999;this.d.parentNode.style.zIndex=9999;if(a>this.q&&(c==0||c==3))this.d.style.left="-"+(a-this.q)+"px";if(b>this.p&&(c==1||c==0))this.d.style.top="-"+(b-this.p)+"px";this.R=m};
W.prototype.Ua=function(a,b){var c=zb(this.d),d=pb(window),e=a-this.q,f=b-this.p,h=c.y,j=f>h,k=d.height-(c.y+this.p),l=j||k>=h,n=c.x,p=e>n,q=d.width-(c.x+this.q),w=p||q>=n,L=0;if(l&&w)L=2;else if(l&&!w)L=3;else if(!l&&w)L=1;else if(!l&&!w)L=0;return L};xa("ExpandableAdSlot",W);var Nc=0;function Oc(a){return a!=i?'"'+a+'"':'""'}function ha(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function X(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function Y(a){var b=window,c=ba[a]||ca[a]||i,d=b[a];X(c,d)}function Z(a,b){b!=i&&X(a,ha(b))}function $(a){var b=window,c=ba[a]||ca[a]||i,d=b[a];Z(c,d)}function Pc(a,b){var c=window,d=ba[a]||ca[a]||i,e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];X(d,e)}
function Qc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){X("u_h",b.height);X("u_w",b.width);X("u_ah",b.availHeight);X("u_aw",b.availWidth);X("u_cd",b.colorDepth)}X("u_tz",d);X("u_his",history.length);X("u_java",c);navigator.plugins&&X("u_nplug",navigator.plugins.length);navigator.mimeTypes&&X("u_nmime",navigator.mimeTypes.length)}
function Rc(a){if(!a.google_enable_first_party_cookie)return;if(o==i)o=new da;if(a._GA_googleCookieHelper==i)a._GA_googleCookieHelper=new r;if(!a._google_cookie_fetched){a._google_cookie_fetched=m;a._GA_googleCookieHelper.Xa(Sc(a.google_ad_client))}}function Sc(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function Tc(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}
function Uc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}function Vc(){var a=z&&B("6")&&!B("8"),b=fb&&B("1.8.1"),c=A&&B("525");if(Xa&&(a||b||c))return m;else if(Wa&&(c||b))return m;else if(Ya&&b)return m;return g}function Wc(a,b){var c=a.google_allow_expandable_ads;if(c!=i&&c==g||!b.body||a.google_ad_output!="html"||Xc(a,b)||Yc(a)||Zc(a.google_ad_format)||!Vc())return g;return m}
function $c(){var a=Math.random();if(a<0.03)return 30143001;else if(a<0.06)return 30143002;return 0}function ad(){var a=Math.random();if(a<0.01)return 30143003;else if(a<0.02)return 30143004;else if(a<0.03)return 30143005;else if(a<0.04)return 30143006;else if(a<0.05)return 30143007;else if(a<0.06)return 30143008;return 0}function bd(a){a.google_allow_expandable_ads=g;a.google_expandable_iframe=g}var cd=Math.random()<0.0010;
function dd(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function ed(a,b,c,d){var e=Uc(a),f=a.google_container_id||d||"google_ad_div"+e;c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var h="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+h+' language="JavaScript1.1" src='+Oc(fd(c))+"></"+h+">");else if(a.google_ad_output=="html")if(b.body&&(a.google_expandable_iframe||Nc==30143002)){var j=gd(f,parseInt(a.google_ad_width,10),parseInt(a.google_ad_height,10),b),k=
hd(e,a,j);a["google_expandable_ad_slot"+e]=new W(fd(c),k)}else{var l='<iframe name="google_ads_frame" width='+Oc(a.google_ad_width)+" height="+Oc(a.google_ad_height)+" frameborder="+Oc(a.google_ad_frameborder)+" src="+Oc(fd(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?id(a.google_container_id,b,l):b.write(l)}else a.google_ad_output=="textlink"&&b.write("<"+h+' language="JavaScript1.1" src='+Oc(fd(c))+"></"+h+
">");if(cd){var n=jd(a)+"/pagead/gen_204?id=ifjs2&token="+a.google_correlator+"&output="+ha(a.google_ad_output)+"&url="+ha(a.google_page_url);dd(a,n)}}function gd(a,b,c,d){var e=mb(a);if(e){e.style.display="block";e.style.height=c+"px";e.style.visibility="visible";e.style.width=b+"px"}else{d.write('<ins id="'+a+'" style="width:'+b+"px;height:"+c+'px;position:relative;margin:0;padding:0;display:block;visibility:visible;border:none"></ins>');e=mb(a)}return e}
function hd(a,b,c){var d=ib().createElement("IFRAME");d.id="google_ads_frame"+a;d.allowTransparency=m;d.frameBorder=b.google_ad_frameborder||0;d.height=b.google_ad_height;d.hspace=0;d.marginHeight=0;d.marginWidth=0;d.name="google_ads_frame";d.scrolling="no";d.style.left=0;d.style.position="absolute";d.style.top=0;d.vspace=0;d.width=b.google_ad_width;c.appendChild(d);return d}function kd(a){for(var b in ba)a[b]=i;for(var b in ca){if(b=="google_correlator")continue;a[b]=i}a.google_container_id=i}
function Yc(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function Zc(a){return a&&a.indexOf("_sdo")!=-1}
function ld(a){var b=i,c=window,d=document,e=aa,f=c.google_ad_format,h=jd(c),j;if(c.google_cpa_choice!=b){c.google_ad_url=h+"/cpa/ads?";j=escape(Sc(c.google_ad_client));c.google_ad_region="_google_cpa_region_";Y("google_cpa_choice");if(typeof d.characterSet!="undefined")Z("oe",d.characterSet);else typeof d.charset!="undefined"&&Z("oe",d.charset)}else if(Zc(f)){c.google_ad_url=h+"/pagead/sdo?";j=escape(Tc(c.google_ad_client))}else{c.google_ad_url=h+"/pagead/ads?";j=escape(Sc(c.google_ad_client))}c.google_ad_url+=
"client="+j;Y("google_ad_host");Y("google_ad_host_tier_id");var k=c.google_num_slots_by_client,l=c.google_num_slots_by_channel,n=c.google_prev_ad_formats_by_region,p=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var q=c.google_ad_region==b?"":c.google_ad_region;if(Zc(f)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>4)return g}else if(Yc(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?
c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return g}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){n[q]=b;p[q]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=e%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return g}else if(c.google_num_ad_slots>6&&q=="")return g}X("dt",aa);Y("google_language");c.google_country?Y("google_country"):Y("google_gl");Y("google_region");
$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");var w=c.google_ad_client;if(k[w])k[w]+=1;else{k[w]=1;k.length+=1}if(n[q])if(!Zc(f)){Z("prev_fmts",n[q].toLowerCase());k.length>1&&X("slot",k[w])}p[q]&&Z("prev_slotnames",p[q].toLowerCase());if(f&&!c.google_ad_slot){Z("format",f.toLowerCase());Zc(f)||(n[q]=n[q]?n[q]+","+f:f)}if(c.google_ad_slot)p[q]=p[q]?
p[q]+","+c.google_ad_slot:c.google_ad_slot;Y("google_max_num_ads");X("output",c.google_ad_output);Y("google_adtest");Y("google_ad_callback");Y("google_ad_slot");$("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&X("dblk",1);if(c.google_ad_channel){$("google_ad_channel");var L="",Yb=c.google_ad_channel.split(md);for(var bb=0;bb<Yb.length;bb++){var cb=Yb[bb];if(l[cb])L+=cb+"+";else l[cb]=1}Z("pv_ch",L)}if(c.google_ad_host_channel){$("google_ad_host_channel");var ud=
nd(c.google_ad_host_channel,c.google_viewed_host_channels);Z("pv_h_ch",ud)}c.google_enable_first_party_cookie&&Z("cookie",c._GA_googleCookieHelper.cb());$("google_page_url");Pc("google_color_bg",e);Pc("google_color_text",e);Pc("google_color_link",e);Pc("google_color_url",e);Pc("google_color_border",e);Pc("google_color_line",e);c.google_reuse_colors?X("reuse_colors",1):X("reuse_colors",0);Y("google_kw_type");$("google_kw");$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");
Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");Y("google_ad_region");if(!Wc(c,d))bd(c);else if(c.google_expandable_iframe===g)bd(c);else if(j in{"ca-pub-2944451727872625":1,"ca-pub-9483266128490610":1,"ca-pub-1955924717845427":1,"ca-pub-6664249124335298":1})c.google_expandable_iframe=m;else if(!(c.google_expandable_iframe==m)){Nc=$c();X("eid",Nc);bd(c)}var Zb=c.google_allow_expandable_ads;if(Zb!=i)Zb?X("ea","1"):
X("ea","0");if(Nc==0){Nc=ad();X("eid",Nc)}Y("google_feedback");$("google_referrer_url");$("google_page_location");X("frm",c.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");$("google_only_ads_with_video");
$("google_disable_video_autoplay");if(a){Z("ff",Ab(a));var db=yb(a),eb=pb();if(db&&eb){Z("biw",eb.width);Z("bih",eb.height);Z("adx",db.x);Z("ady",db.y)}}Cb();X("ga_vid",c.gaGlobal.vid);X("ga_sid",c.gaGlobal.sid);X("ga_hid",c.gaGlobal.hid);X("ga_fc",c.gaGlobal.from_cookie);$("google_analytics_uacct");Y("google_ad_override");Y("google_flash_version");Qc(c);cd&&X("gen_204","ifjs2");return m}
function nd(a,b){var c=a.split("|"),d=-1,e=[];for(var f=0;f<c.length;f++){var h=c[f].split(md);b[f]||(b[f]={});var j="";for(var k=0;k<h.length;k++){var l=h[k];if(b[f][l])j+="+"+l;else b[f][l]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var n="";if(d>-1){for(var f=0;f<d;f++)n+=e[f]+"|";n+=e[d]}return n}
function od(){var a=window,b=document;Rc(a);var c;if(Math.random()<0.01){var d="google_temp_span";if(!mb(d)){b.write("<span id="+d+"></span>");c=mb(d)}}var e=ld(c);c&&D(c);if(!e)return;ed(a,b,a.google_ad_url);kd(a)}function fd(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c}function pd(){od();return m}
function Xc(a,b){if(a.top.location==b.location)return g;var c=b.documentElement;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return g}return m}
function qd(a){var b=window,c=i,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(Zc(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;rd(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=aa;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=ja();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function ka(a){if(a in sd)return sd[a];return sd[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var sd={};
function td(a){var b={},c=a.split("?"),d=c[c.length-1].split("&");for(var e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(h){}}return b}function vd(){var a=window,b=td(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function wd(a,b){for(var c in b)a["google_"+c]=b[c]}
function xd(a,b){if(!b)return a.location;return a.referrer}function yd(a,b){if(!b&&a.google_referrer_url==i)return"0";else if(b&&a.google_referrer_url==i)return"1";else if(!b&&a.google_referrer_url!=i)return"2";else if(b&&a.google_referrer_url!=i)return"3";return"4"}function zd(a,b,c,d){a.page_url=xd(c,d);a.page_location=i}function Ad(a,b,c,d){a.page_url=b.google_page_url;a.page_location=xd(c,d)||"EMPTY"}
function Bd(a,b){var c={},d=Xc(a,b);c.iframing=yd(a,d);!!a.google_page_url?Ad(c,a,b,d):zd(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:i;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Cd(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=i;b.page_url=c;b.page_location=a.location;b.last_modified_time=i;b.referrer_url=c;return b}
function rd(a,b){var c;c=a.google_page_url==i&&Dd[b.domain]?Cd(b):Bd(a,b);wd(a,c)}function id(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var Dd={};Dd["ad.yieldmanager.com"]=m;var md=/[+, ]/;window.google_render_ad=od;var Ed={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};function Fd(a){var b=a.google_page_location||a.google_page_url;if(!b)return g;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=g;if(e.length>=3)f=e[e.length-3]in Ed;if(e.length>=2)f=f||e[e.length-2]in Ed;return f}
function Gd(a,b,c){if(a.google_new_domain_checked==0){a.google_random_number=Math.random();if(a.google_random_number<c){var d="http://googleads.g.doubleclick.net/pagead/test_domain.js",e="script";b.write("<"+e+' src="'+d+'"></'+e+">");a.google_new_domain_checked=1}}}function jd(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!Fd(a)&&a.google_new_domain_enabled==1)return b;return c};vd();qd(pd);Gd(window,document,ia("0.05",0.01));var Hd="script";document.write("<"+Hd+"> window.google_render_ad(); </"+Hd+">");
})()
